In [1]:
import pandas as pd

In [2]:
geodata = pd.read_csv("../../templates/resources/data/masterdata.csv")

In [3]:
geodata = geodata.drop(columns=["Lat", "Lng"])

In [4]:
geodata

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,coordinates
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.3,77640.0,36787.0,76933.0,10.437707,Alaska,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.7,58945.0,30694.0,1043764.0,14.804535,Arizona,"{'type': 'Polygon', 'coordinates': [[[-109.045..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.1,47597.0,26577.0,496260.0,16.545475,Arkansas,"{'type': 'Polygon', 'coordinates': [[[-94.5592..."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.7,72331.0,38226.0,565873.0,10.086235,Colorado,"{'type': 'Polygon', 'coordinates': [[[-102.042..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.6,68287.0,35450.0,109400.0,11.428595,Delaware,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.1,81275.0,35567.0,130649.0,9.187086,Florida,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,"{'type': 'Polygon', 'coordinates': [[[-81.4441..."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.7,58700.0,31067.0,1528558.0,14.692238,Hawaii,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.4,55785.0,27970.0,221256.0,12.880571,Idaho,"{'type': 'Polygon', 'coordinates': [[[-111.046..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.1,65886.0,36038.0,1557873.0,12.198873,Illinois,"{'type': 'Polygon', 'coordinates': [[[-87.5323..."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.7,56303.0,29777.0,867996.0,13.021822,Indiana,"{'type': 'Polygon', 'coordinates': [[[-88.0280..."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.2,60523.0,32176.0,348122.0,11.088425,Iowa,"{'type': 'Polygon', 'coordinates': [[[-95.7656..."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.7,59597.0,31814.0,337739.0,11.603551,Kansas,"{'type': 'Polygon', 'coordinates': [[[-94.6180..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.9,50589.0,28178.0,747010.0,16.790318,Kentucky,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.9,49469.0,27923.0,871467.0,18.683520,Louisiana,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.7,57918.0,32637.0,153131.0,11.466261,Maine,"{'type': 'MultiPolygon', 'coordinates': [[[[-6..."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.7,84805.0,42122.0,539991.0,8.971667,Maryland,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.7,57144.0,31713.0,1398527.0,14.034017,Michigan,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,"{'type': 'Polygon', 'coordinates': [[[-91.3716..."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.6,55461.0,30810.0,810045.0,13.268746,Missouri,"{'type': 'Polygon', 'coordinates': [[[-89.5391..."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.9,54970.0,31151.0,134605.0,12.811605,Montana,"{'type': 'Polygon', 'coordinates': [[[-104.057..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,"{'type': 'Polygon', 'coordinates': [[[-95.7656..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,"{'type': 'Polygon', 'coordinates': [[[-114.050..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.9,76768.0,40003.0,98682.0,7.319950,New Hampshire,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.9,82545.0,42745.0,869081.0,9.788598,New Jersey,"{'type': 'Polygon', 'coordinates': [[[-75.5268..."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.8,49754.0,27230.0,392065.0,18.737091,New Mexico,"{'type': 'Polygon', 'coordinates': [[[-109.050..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.7,54602.0,30783.0,1467591.0,14.297211,New York,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.1,64894.0,36062.0,78198.0,10.333850,North Carolina,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.8,68486.0,39326.0,2681277.0,13.699332,North Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.5632..."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.4,56602.0,31552.0,1588343.0,13.627532,Ohio,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.6,52919.0,28422.0,598373.0,15.214665,Oklahoma,"{'type': 'Polygon', 'coordinates': [[[-94.6179..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.3,62818.0,33763.0,533527.0,12.918946,Oregon,"{'type': 'Polygon', 'coordinates': [[[-117.220..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.8,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,"{'type': 'Polygon', 'coordinates': [[[-75.4150..."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.9,67167.0,36121.0,125826.0,11.901467,Rhode Island,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.4,53199.0,29426.0,741650.0,14.771533,South Carolina,"{'type': 'Polygon', 'coordinates': [[[-78.5410..."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.4434..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.7,53320.0,29859.0,996930.0,14.858803,Tennessee,"{'type': 'Polygon', 'coordinates': [[[-81.6775..."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.6,61874.0,31277.0,4072194.0,14.409309,Texas,"{'type': 'MultiPolygon', 'coordinates': [[[[-9..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.8,71621.0,29775.0,298537.0,9.640028,Utah,"{'type': 'Polygon', 'coordinates': [[[-114.050..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.9,61973.0,34577.0,65652.0,10.515879,Vermont,"{'type': 'Polygon', 'coordinates': [[[-72.0400..."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.2,74222.0,39278.0,865691.0,10.239456,Virginia,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.7,73775.0,38915.0,785244.0,10.605519,Washington,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,"{'type': 'Polygon', 'coordinates': [[[-81.9682..."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,"{'type': 'MultiPolygon', 'coordinates': [[[[-9..."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.7,64049.0,33366.0,62257.0,10.715048,Wyoming,"{'type': 'Polygon', 'coordinates': [[[-109.050..."

In [5]:
geodata = geodata.rename(columns={"coordinates":"geometry"})
geodata

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.3,77640.0,36787.0,76933.0,10.437707,Alaska,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.7,58945.0,30694.0,1043764.0,14.804535,Arizona,"{'type': 'Polygon', 'coordinates': [[[-109.045..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.1,47597.0,26577.0,496260.0,16.545475,Arkansas,"{'type': 'Polygon', 'coordinates': [[[-94.5592..."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.7,72331.0,38226.0,565873.0,10.086235,Colorado,"{'type': 'Polygon', 'coordinates': [[[-102.042..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.6,68287.0,35450.0,109400.0,11.428595,Delaware,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.1,81275.0,35567.0,130649.0,9.187086,Florida,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,"{'type': 'Polygon', 'coordinates': [[[-81.4441..."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.7,58700.0,31067.0,1528558.0,14.692238,Hawaii,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.4,55785.0,27970.0,221256.0,12.880571,Idaho,"{'type': 'Polygon', 'coordinates': [[[-111.046..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.1,65886.0,36038.0,1557873.0,12.198873,Illinois,"{'type': 'Polygon', 'coordinates': [[[-87.5323..."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.7,56303.0,29777.0,867996.0,13.021822,Indiana,"{'type': 'Polygon', 'coordinates': [[[-88.0280..."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.2,60523.0,32176.0,348122.0,11.088425,Iowa,"{'type': 'Polygon', 'coordinates': [[[-95.7656..."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.7,59597.0,31814.0,337739.0,11.603551,Kansas,"{'type': 'Polygon', 'coordinates': [[[-94.6180..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.9,50589.0,28178.0,747010.0,16.790318,Kentucky,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.9,49469.0,27923.0,871467.0,18.683520,Louisiana,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.7,57918.0,32637.0,153131.0,11.466261,Maine,"{'type': 'MultiPolygon', 'coordinates': [[[[-6..."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.7,84805.0,42122.0,539991.0,8.971667,Maryland,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.7,57144.0,31713.0,1398527.0,14.034017,Michigan,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,"{'type': 'Polygon', 'coordinates': [[[-91.3716..."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.6,55461.0,30810.0,810045.0,13.268746,Missouri,"{'type': 'Polygon', 'coordinates': [[[-89.5391..."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.9,54970.0,31151.0,134605.0,12.811605,Montana,"{'type': 'Polygon', 'coordinates': [[[-104.057..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,"{'type': 'Polygon', 'coordinates': [[[-95.7656..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,"{'type': 'Polygon', 'coordinates': [[[-114.050..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.9,76768.0,40003.0,98682.0,7.319950,New Hampshire,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.9,82545.0,42745.0,869081.0,9.788598,New Jersey,"{'type': 'Polygon', 'coordinates': [[[-75.5268..."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.8,49754.0,27230.0,392065.0,18.737091,New Mexico,"{'type': 'Polygon', 'coordinates': [[[-109.050..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.7,54602.0,30783.0,1467591.0,14.297211,New York,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.1,64894.0,36062.0,78198.0,10.333850,North Carolina,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.8,68486.0,39326.0,2681277.0,13.699332,North Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.5632..."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.4,56602.0,31552.0,1588343.0,13.627532,Ohio,"{'type': 'MultiPolygon', 'coordinates': [[[[-8..."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.6,52919.0,28422.0,598373.0,15.214665,Oklahoma,"{'type': 'Polygon', 'coordinates': [[[-94.6179..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.3,62818.0,33763.0,533527.0,12.918946,Oregon,"{'type': 'Polygon', 'coordinates': [[[-117.220..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.8,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,"{'type': 'Polygon', 'coordinates': [[[-75.4150..."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.9,67167.0,36121.0,125826.0,11.901467,Rhode Island,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.4,53199.0,29426.0,741650.0,14.771533,South Carolina,"{'type': 'Polygon', 'coordinates': [[[-78.5410..."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.4434..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.7,53320.0,29859.0,996930.0,14.858803,Tennessee,"{'type': 'Polygon', 'coordinates': [[[-81.6775..."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.6,61874.0,31277.0,4072194.0,14.409309,Texas,"{'type': 'MultiPolygon', 'coordinates': [[[[-9..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.8,71621.0,29775.0,298537.0,9.640028,Utah,"{'type': 'Polygon', 'coordinates': [[[-114.050..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.9,61973.0,34577.0,65652.0,10.515879,Vermont,"{'type': 'Polygon', 'coordinates': [[[-72.0400..."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.2,74222.0,39278.0,865691.0,10.239456,Virginia,"{'type': 'MultiPolygon', 'coordinates': [[[[-7..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.7,73775.0,38915.0,785244.0,10.605519,Washington,"{'type': 'MultiPolygon', 'coordinates': [[[[-1..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,"{'type': 'Polygon', 'coordinates': [[[-81.9682..."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,"{'type': 'MultiPolygon', 'coordinates': [[[[-9..."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.7,64049.0,33366.0,62257.0,10.715048,Wyoming,"{'type': 'Polygon', 'coordinates': [[[-109.050..."

In [7]:
# Saving to CSV
geodata.to_csv("../../templates/resources/data/masterdata2.csv", index=False)

In [ ]:
geo_dict = geodata.to_dict()

In [ ]:
geo_dict["geometry"]

In [ ]:
# pop min
x = geodata["Population"].min()
x

In [ ]:
# pop max
y = geodata["Population"].max()
y

In [ ]:
# pop mean
z = geodata["Population"].mean()
z

In [ ]:
# pop low mid
a = z-x
a

In [ ]:
# pop high mid
b = y-z
b

In [ ]:
# min = x
# low mid = a
# mean = z
# high mid = b
# max = y

# This is where we read in data using geopandas (to read the geojson)

In [8]:
import geopandas as gpd

In [10]:
geojson_data = gpd.read_file('../../templates/resources/chloropleth_files/static/data/statesData.geojson')
geojson_data

,id,name,density,geometry
0,01,Alabama,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,02,Alaska,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,04,Arizona,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,05,Arkansas,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,06,California,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,08,Colorado,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,09,Connecticut,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,10,Delaware,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,11,District of Columbia,10065.000,"POLYGON ((-77.035 38.994, -76.909 38.895, -77...."
9,12,Florida,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
10,13,Georgia,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
11,15,Hawaii,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
12,16,Idaho,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
13,17,Illinois,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
14,18,Indiana,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
15,19,Iowa,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
16,20,Kansas,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
17,21,Kentucky,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
18,22,Louisiana,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
19,23,Maine,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
20,24,Maryland,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
21,25,Massachusetts,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
22,26,Michigan,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
23,27,Minnesota,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
24,28,Mississippi,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
25,29,Missouri,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
26,30,Montana,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
27,31,Nebraska,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
28,32,Nevada,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
29,33,New Hampshire,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
30,34,New Jersey,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
31,35,New Mexico,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
32,36,New York,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
33,37,North Carolina,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
34,38,North Dakota,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
35,39,Ohio,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
36,40,Oklahoma,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
37,41,Oregon,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
38,42,Pennsylvania,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
39,44,Rhode Island,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
40,45,South Carolina,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
41,46,South Dakota,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
42,47,Tennessee,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
43,48,Texas,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
44,49,Utah,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
45,50,Vermont,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
46,51,Virginia,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
47,53,Washington,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
48,54,West Virginia,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
49,55,Wisconsin,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
50,56,Wyoming,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."
51,72,Puerto Rico,1082.000,"POLYGON ((-66.448 17.984, -66.771 18.006, -66...."

In [11]:
geojson_data = geojson_data.rename(columns={"name":"state"})
geojson_data

,id,state,density,geometry
0,01,Alabama,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,02,Alaska,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,04,Arizona,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,05,Arkansas,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,06,California,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,08,Colorado,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,09,Connecticut,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,10,Delaware,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,11,District of Columbia,10065.000,"POLYGON ((-77.035 38.994, -76.909 38.895, -77...."
9,12,Florida,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
10,13,Georgia,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
11,15,Hawaii,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
12,16,Idaho,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
13,17,Illinois,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
14,18,Indiana,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
15,19,Iowa,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
16,20,Kansas,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
17,21,Kentucky,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
18,22,Louisiana,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
19,23,Maine,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
20,24,Maryland,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
21,25,Massachusetts,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
22,26,Michigan,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
23,27,Minnesota,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
24,28,Mississippi,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
25,29,Missouri,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
26,30,Montana,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
27,31,Nebraska,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
28,32,Nevada,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
29,33,New Hampshire,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
30,34,New Jersey,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
31,35,New Mexico,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
32,36,New York,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
33,37,North Carolina,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
34,38,North Dakota,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
35,39,Ohio,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
36,40,Oklahoma,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
37,41,Oregon,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
38,42,Pennsylvania,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
39,44,Rhode Island,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
40,45,South Carolina,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
41,46,South Dakota,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
42,47,Tennessee,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
43,48,Texas,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
44,49,Utah,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
45,50,Vermont,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
46,51,Virginia,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
47,53,Washington,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
48,54,West Virginia,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
49,55,Wisconsin,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
50,56,Wyoming,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."
51,72,Puerto Rico,1082.000,"POLYGON ((-66.448 17.984, -66.771 18.006, -66...."

In [ ]:
# # min
# a = geojson_data["density"].min()
# a

In [ ]:
# # low-mid
# b = (c+a)/2
# b

In [ ]:
# # mean
# c = geojson_data["density"].mean()
# c

In [ ]:
# # high-mid
# d = (e-c)/2
# d

In [ ]:
# # max
# e = geojson_data["density"].max()
# e

In [12]:
master_data = gpd.read_file('../../templates/resources/chloropleth_files/static/data/masterdata.geojson')
master_data

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,coordinates,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-86.30057 32.37772)
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.299999999999997,77640.0,36787.0,76933.0,10.437707,Alaska,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-134.42021 58.30160)
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.700000000000003,58945.0,30694.0,1043764.0,14.804535,Arizona,"{'type': 'Polygon', 'coordinates': [[[-109.045...",POINT (-112.09696 33.44814)
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.100000000000001,47597.0,26577.0,496260.0,16.545475,Arkansas,"{'type': 'Polygon', 'coordinates': [[[-94.5592...",POINT (-92.28899 34.74661)
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-121.49363 38.57667)
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.700000000000003,72331.0,38226.0,565873.0,10.086235,Colorado,"{'type': 'Polygon', 'coordinates': [[[-102.042...",POINT (-104.98486 39.73923)
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-72.68220 41.76405)
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.600000000000001,68287.0,35450.0,109400.0,11.428595,Delaware,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-75.51972 39.15731)
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.100000000000001,81275.0,35567.0,130649.0,9.187086,Florida,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-157.85738 21.30744)
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,"{'type': 'Polygon', 'coordinates': [[[-81.4441...",POINT (-84.28130 30.43812)
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.700000000000003,58700.0,31067.0,1528558.0,14.692238,Hawaii,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-84.38823 33.74903)
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.399999999999999,55785.0,27970.0,221256.0,12.880571,Idaho,"{'type': 'Polygon', 'coordinates': [[[-111.046...",POINT (-116.19972 43.61778)
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.100000000000001,65886.0,36038.0,1557873.0,12.198873,Illinois,"{'type': 'Polygon', 'coordinates': [[[-87.5323...",POINT (-89.65496 39.79836)
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.700000000000003,56303.0,29777.0,867996.0,13.021822,Indiana,"{'type': 'Polygon', 'coordinates': [[[-88.0280...",POINT (-86.16264 39.76862)
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.200000000000003,60523.0,32176.0,348122.0,11.088425,Iowa,"{'type': 'Polygon', 'coordinates': [[[-95.7656...",POINT (-93.60373 41.59109)
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.700000000000003,59597.0,31814.0,337739.0,11.603551,Kansas,"{'type': 'Polygon', 'coordinates': [[[-94.6180...",POINT (-95.67796 39.04819)
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.899999999999999,50589.0,28178.0,747010.0,16.790318,Kentucky,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-84.87537 38.18672)
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.899999999999999,49469.0,27923.0,871467.0,18.683520,Louisiana,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-91.18739 30.45707)
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.700000000000003,57918.0,32637.0,153131.0,11.466261,Maine,"{'type': 'MultiPolygon', 'coordinates': [[[[-6...",POINT (-69.78169 44.30717)
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.700000000000003,84805.0,42122.0,539991.0,8.971667,Maryland,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-76.49094 38.97876)
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.06370 42.35816)
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.700000000000003,57144.0,31713.0,1398527.0,14.034017,Michigan,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-84.55533 42.73363)
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,"{'type': 'Polygon', 'coordinates': [[[-91.3716...",POINT (-93.10221 44.95510)
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-90.18211 32.30385)
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.600000000000001,55461.0,30810.0,810045.0,13.268746,Missouri,"{'type': 'Polygon', 'coordinates': [[[-89.5391...",POINT (-92.17293 38.57920)
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.899999999999999,54970.0,31151.0,134605.0,12.811605,Montana,"{'type': 'Polygon', 'coordinates': [[[-104.057...",POINT (-112.01842 46.58571)
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,"{'type': 'Polygon', 'coordinates': [[[-95.7656...",POINT (-96.69965 40.80808)
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,"{'type': 'Polygon', 'coordinates': [[[-114.050...",POINT (-119.76612 39.16391)
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.899999999999999,76768.0,40003.0,98682.0,7.319950,New Hampshire,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.53799 43.20690)
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.899999999999999,82545.0,42745.0,869081.0,9.788598,New Jersey,"{'type': 'Polygon', 'coordinates': [[[-75.5268...",POINT (-74.76991 40.22060)
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.799999999999997,49754.0,27230.0,392065.0,18.737091,New Mexico,"{'type': 'Polygon', 'coordinates': [[[-109.050...",POINT (-105.93973 35.68224)
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.700000000000003,54602.0,30783.0,1467591.0,14.297211,New York,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-78.63910 35.78043)
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.100000000000001,64894.0,36062.0,78198.0,10.333850,North Carolina,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-100.78332 46.82085)
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.799999999999997,68486.0,39326.0,2681277.0,13.699332,North Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.5632...",POINT (-73.75787 42.65284)
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.399999999999999,56602.0,31552.0,1588343.0,13.627532,Ohio,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-82.99907 39.96135)
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.600000000000001,52919.0,28422.0,598373.0,15.214665,Oklahoma,"{'type': 'Polygon', 'coordinates': [[[-94.6179...",POINT (-97.50334 35.49221)
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.299999999999997,62818.0,33763.0,533527.0,12.918946,Oregon,"{'type': 'Polygon', 'coordinates': [[[-117.220...",POINT (-123.03040 44.93846)
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.799999999999997,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,"{'type': 'Polygon', 'coordinates': [[[-75.4150...",POINT (-76.88360 40.26438)
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.899999999999999,67167.0,36121.0,125826.0,11.901467,Rhode Island,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.41496 41.83091)
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.399999999999999,53199.0,29426.0,741650.0,14.771533,South Carolina,"{'type': 'Polygon', 'coordinates': [[[-78.5410...",POINT (-81.03321 34.00034)
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.4434...",POINT (-100.34641 44.36703)
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.700000000000003,53320.0,29859.0,996930.0,14.858803,Tennessee,"{'type': 'Polygon', 'coordinates': [[[-81.6775...",POINT (-86.78424 36.16581)
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.600000000000001,61874.0,31277.0,4072194.0,14.409309,Texas,"{'type': 'MultiPolygon', 'coordinates': [[[[-9...",POINT (-97.74035 30.27467)
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.800000000000001,71621.0,29775.0,298537.0,9.640028,Utah,"{'type': 'Polygon', 'coordinates': [[[-114.050...",POINT (-111.88824 40.77748)
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.899999999999999,61973.0,34577.0,65652.0,10.515879,Vermont,"{'type': 'Polygon', 'coordinates': [[[-72.0400...",POINT (-72.58054 44.26244)
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.200000000000003,74222.0,39278.0,865691.0,10.239456,Virginia,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-77.43364 37.53886)
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.700000000000003,73775.0,38915.0,785244.0,10.605519,Washington,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-122.90501 47.03580)
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,"{'type': 'Polygon', 'coordinates': [[[-81.9682...",POINT (-81.61233 38.33625)
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,"{'type': 'MultiPolygon', 'coordinates': [[[[-9...",POINT (-89.38444 43.07468)
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.700000000000003,64049.0,33366.0,62257.0,10.715048,Wyoming,"{'type': 'Polygon', 'coordinates': [[[-109.050...",POINT (-104.82024 41.14026)

In [13]:
x = pd.merge(master_data, geojson_data, on="state")
x

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,coordinates,geometry_x,id,density,geometry_y
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-86.30057 32.37772),01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.299999999999997,77640.0,36787.0,76933.0,10.437707,Alaska,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-134.42021 58.30160),02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.700000000000003,58945.0,30694.0,1043764.0,14.804535,Arizona,"{'type': 'Polygon', 'coordinates': [[[-109.045...",POINT (-112.09696 33.44814),04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.100000000000001,47597.0,26577.0,496260.0,16.545475,Arkansas,"{'type': 'Polygon', 'coordinates': [[[-94.5592...",POINT (-92.28899 34.74661),05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-121.49363 38.57667),06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.700000000000003,72331.0,38226.0,565873.0,10.086235,Colorado,"{'type': 'Polygon', 'coordinates': [[[-102.042...",POINT (-104.98486 39.73923),08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-72.68220 41.76405),09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.600000000000001,68287.0,35450.0,109400.0,11.428595,Delaware,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-75.51972 39.15731),10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.100000000000001,81275.0,35567.0,130649.0,9.187086,Florida,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-157.85738 21.30744),12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,"{'type': 'Polygon', 'coordinates': [[[-81.4441...",POINT (-84.28130 30.43812),13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.700000000000003,58700.0,31067.0,1528558.0,14.692238,Hawaii,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-84.38823 33.74903),15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.399999999999999,55785.0,27970.0,221256.0,12.880571,Idaho,"{'type': 'Polygon', 'coordinates': [[[-111.046...",POINT (-116.19972 43.61778),16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.100000000000001,65886.0,36038.0,1557873.0,12.198873,Illinois,"{'type': 'Polygon', 'coordinates': [[[-87.5323...",POINT (-89.65496 39.79836),17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.700000000000003,56303.0,29777.0,867996.0,13.021822,Indiana,"{'type': 'Polygon', 'coordinates': [[[-88.0280...",POINT (-86.16264 39.76862),18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.200000000000003,60523.0,32176.0,348122.0,11.088425,Iowa,"{'type': 'Polygon', 'coordinates': [[[-95.7656...",POINT (-93.60373 41.59109),19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.700000000000003,59597.0,31814.0,337739.0,11.603551,Kansas,"{'type': 'Polygon', 'coordinates': [[[-94.6180...",POINT (-95.67796 39.04819),20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.899999999999999,50589.0,28178.0,747010.0,16.790318,Kentucky,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-84.87537 38.18672),21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.899999999999999,49469.0,27923.0,871467.0,18.683520,Louisiana,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-91.18739 30.45707),22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.700000000000003,57918.0,32637.0,153131.0,11.466261,Maine,"{'type': 'MultiPolygon', 'coordinates': [[[[-6...",POINT (-69.78169 44.30717),23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.700000000000003,84805.0,42122.0,539991.0,8.971667,Maryland,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-76.49094 38.97876),24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.06370 42.35816),25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.700000000000003,57144.0,31713.0,1398527.0,14.034017,Michigan,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-84.55533 42.73363),26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,"{'type': 'Polygon', 'coordinates': [[[-91.3716...",POINT (-93.10221 44.95510),27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-90.18211 32.30385),28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.600000000000001,55461.0,30810.0,810045.0,13.268746,Missouri,"{'type': 'Polygon', 'coordinates': [[[-89.5391...",POINT (-92.17293 38.57920),29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.899999999999999,54970.0,31151.0,134605.0,12.811605,Montana,"{'type': 'Polygon', 'coordinates': [[[-104.057...",POINT (-112.01842 46.58571),30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,"{'type': 'Polygon', 'coordinates': [[[-95.7656...",POINT (-96.69965 40.80808),31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,"{'type': 'Polygon', 'coordinates': [[[-114.050...",POINT (-119.76612 39.16391),32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.899999999999999,76768.0,40003.0,98682.0,7.319950,New Hampshire,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.53799 43.20690),33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.899999999999999,82545.0,42745.0,869081.0,9.788598,New Jersey,"{'type': 'Polygon', 'coordinates': [[[-75.5268...",POINT (-74.76991 40.22060),34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.799999999999997,49754.0,27230.0,392065.0,18.737091,New Mexico,"{'type': 'Polygon', 'coordinates': [[[-109.050...",POINT (-105.93973 35.68224),35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.700000000000003,54602.0,30783.0,1467591.0,14.297211,New York,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-78.63910 35.78043),36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.100000000000001,64894.0,36062.0,78198.0,10.333850,North Carolina,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-100.78332 46.82085),37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.799999999999997,68486.0,39326.0,2681277.0,13.699332,North Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.5632...",POINT (-73.75787 42.65284),38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.399999999999999,56602.0,31552.0,1588343.0,13.627532,Ohio,"{'type': 'MultiPolygon', 'coordinates': [[[[-8...",POINT (-82.99907 39.96135),39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.600000000000001,52919.0,28422.0,598373.0,15.214665,Oklahoma,"{'type': 'Polygon', 'coordinates': [[[-94.6179...",POINT (-97.50334 35.49221),40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.299999999999997,62818.0,33763.0,533527.0,12.918946,Oregon,"{'type': 'Polygon', 'coordinates': [[[-117.220...",POINT (-123.03040 44.93846),41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.799999999999997,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,"{'type': 'Polygon', 'coordinates': [[[-75.4150...",POINT (-76.88360 40.26438),42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.899999999999999,67167.0,36121.0,125826.0,11.901467,Rhode Island,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-71.41496 41.83091),44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.399999999999999,53199.0,29426.0,741650.0,14.771533,South Carolina,"{'type': 'Polygon', 'coordinates': [[[-78.5410...",POINT (-81.03321 34.00034),45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,"{'type': 'Polygon', 'coordinates': [[[-96.4434...",POINT (-100.34641 44.36703),46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.700000000000003,53320.0,29859.0,996930.0,14.858803,Tennessee,"{'type': 'Polygon', 'coordinates': [[[-81.6775...",POINT (-86.78424 36.16581),47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.600000000000001,61874.0,31277.0,4072194.0,14.409309,Texas,"{'type': 'MultiPolygon', 'coordinates': [[[[-9...",POINT (-97.74035 30.27467),48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.800000000000001,71621.0,29775.0,298537.0,9.640028,Utah,"{'type': 'Polygon', 'coordinates': [[[-114.050...",POINT (-111.88824 40.77748),49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.899999999999999,61973.0,34577.0,65652.0,10.515879,Vermont,"{'type': 'Polygon', 'coordinates': [[[-72.0400...",POINT (-72.58054 44.26244),50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.200000000000003,74222.0,39278.0,865691.0,10.239456,Virginia,"{'type': 'MultiPolygon', 'coordinates': [[[[-7...",POINT (-77.43364 37.53886),51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.700000000000003,73775.0,38915.0,785244.0,10.605519,Washington,"{'type': 'MultiPolygon', 'coordinates': [[[[-1...",POINT (-122.90501 47.03580),53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,"{'type': 'Polygon', 'coordinates': [[[-81.9682...",POINT (-81.61233 38.33625),54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,"{'type': 'MultiPolygon', 'coordinates': [[[[-9...",POINT (-89.38444 43.07468),55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.700000000000003,64049.0,33366.0,62257.0,10.715048,Wyoming,"{'type': 'Polygon', 'coordinates': [[[-109.050...",POINT (-104.82024 41.14026),56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [14]:
x = x.drop(columns=["coordinates", "geometry_x"])
x

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry_y
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.299999999999997,77640.0,36787.0,76933.0,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.700000000000003,58945.0,30694.0,1043764.0,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.100000000000001,47597.0,26577.0,496260.0,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.700000000000003,72331.0,38226.0,565873.0,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.600000000000001,68287.0,35450.0,109400.0,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.100000000000001,81275.0,35567.0,130649.0,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.700000000000003,58700.0,31067.0,1528558.0,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.399999999999999,55785.0,27970.0,221256.0,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.100000000000001,65886.0,36038.0,1557873.0,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.700000000000003,56303.0,29777.0,867996.0,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.200000000000003,60523.0,32176.0,348122.0,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.700000000000003,59597.0,31814.0,337739.0,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.899999999999999,50589.0,28178.0,747010.0,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.899999999999999,49469.0,27923.0,871467.0,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.700000000000003,57918.0,32637.0,153131.0,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.700000000000003,84805.0,42122.0,539991.0,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.700000000000003,57144.0,31713.0,1398527.0,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.600000000000001,55461.0,30810.0,810045.0,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.899999999999999,54970.0,31151.0,134605.0,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.899999999999999,76768.0,40003.0,98682.0,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.899999999999999,82545.0,42745.0,869081.0,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.799999999999997,49754.0,27230.0,392065.0,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.700000000000003,54602.0,30783.0,1467591.0,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.100000000000001,64894.0,36062.0,78198.0,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.799999999999997,68486.0,39326.0,2681277.0,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.399999999999999,56602.0,31552.0,1588343.0,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.600000000000001,52919.0,28422.0,598373.0,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.299999999999997,62818.0,33763.0,533527.0,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.799999999999997,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.899999999999999,67167.0,36121.0,125826.0,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.399999999999999,53199.0,29426.0,741650.0,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.700000000000003,53320.0,29859.0,996930.0,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.600000000000001,61874.0,31277.0,4072194.0,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.800000000000001,71621.0,29775.0,298537.0,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.899999999999999,61973.0,34577.0,65652.0,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.200000000000003,74222.0,39278.0,865691.0,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.700000000000003,73775.0,38915.0,785244.0,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.700000000000003,64049.0,33366.0,62257.0,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

# Re-run this cell below when you need base dataframe

In [15]:
x = x.rename(columns={"geometry_y":"geometry"})
x

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,4876250.0,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,737068.0,34.299999999999997,77640.0,36787.0,76933.0,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,7050299.0,37.700000000000003,58945.0,30694.0,1043764.0,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,2999370.0,38.100000000000001,47597.0,26577.0,496260.0,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497.0,36.5,75235.0,36955.0,5149742.0,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,5610349.0,36.700000000000003,72331.0,38226.0,565873.0,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,3575074.0,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248.0,40.600000000000001,68287.0,35450.0,109400.0,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,1422094.0,39.100000000000001,81275.0,35567.0,130649.0,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,20901636.0,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,10403847.0,36.700000000000003,58700.0,31067.0,1528558.0,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,1717750.0,36.399999999999999,55785.0,27970.0,221256.0,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,12770631.0,38.100000000000001,65886.0,36038.0,1557873.0,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,6665703.0,37.700000000000003,56303.0,29777.0,867996.0,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,3139508.0,38.200000000000003,60523.0,32176.0,348122.0,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,2910652.0,36.700000000000003,59597.0,31814.0,337739.0,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,4449052.0,38.899999999999999,50589.0,28178.0,747010.0,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362.0,36.899999999999999,49469.0,27923.0,871467.0,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492.0,44.700000000000003,57918.0,32637.0,153131.0,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,6018848.0,38.700000000000003,84805.0,42122.0,539991.0,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,6850553.0,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265.0,39.700000000000003,57144.0,31713.0,1398527.0,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378.0,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418.0,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,6104910.0,38.600000000000001,55461.0,30810.0,810045.0,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,1050649.0,39.899999999999999,54970.0,31151.0,134605.0,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571.0,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382.0,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124.0,42.899999999999999,76768.0,40003.0,98682.0,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,8878503.0,39.899999999999999,82545.0,42745.0,869081.0,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,2092454.0,37.799999999999997,49754.0,27230.0,392065.0,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,10264876.0,38.700000000000003,54602.0,30783.0,1467591.0,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717.0,35.100000000000001,64894.0,36062.0,78198.0,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319.0,38.799999999999997,68486.0,39326.0,2681277.0,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397.0,39.399999999999999,56602.0,31552.0,1588343.0,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,3932870.0,36.600000000000001,52919.0,28422.0,598373.0,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,4129803.0,39.299999999999997,62818.0,33763.0,533527.0,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,12791530.0,40.799999999999997,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,1057231.0,39.899999999999999,67167.0,36121.0,125826.0,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,5020806.0,39.399999999999999,53199.0,29426.0,741650.0,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,870638.0,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,6709356.0,38.700000000000003,53320.0,29859.0,996930.0,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,28260856.0,34.600000000000001,61874.0,31277.0,4072194.0,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,3096848.0,30.800000000000001,71621.0,29775.0,298537.0,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313.0,42.899999999999999,61973.0,34577.0,65652.0,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463.0,38.200000000000003,74222.0,39278.0,865691.0,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,7404107.0,37.700000000000003,73775.0,38915.0,785244.0,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,1817305.0,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,5790716.0,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,581024.0,37.700000000000003,64049.0,33366.0,62257.0,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [16]:
master_geojson = x

In [17]:
master_geojson["Population"] = master_geojson["Population"].str.replace(".0", "")
master_geojson["Population"] = master_geojson["Population"].astype(int)
master_geojson

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,48762,39.0,50536.0,27928.0,795989.0,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,7368,34.299999999999997,77640.0,36787.0,76933.0,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,299,37.700000000000003,58945.0,30694.0,1043764.0,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,29993,38.100000000000001,47597.0,26577.0,496260.0,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497,36.5,75235.0,36955.0,5149742.0,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,56349,36.700000000000003,72331.0,38226.0,565873.0,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,35774,41.0,78444.0,44496.0,344146.0,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248,40.600000000000001,68287.0,35450.0,109400.0,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,14294,39.100000000000001,81275.0,35567.0,130649.0,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,1636,42.0,55660.0,31619.0,2870487.0,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,3847,36.700000000000003,58700.0,31067.0,1528558.0,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,17177,36.399999999999999,55785.0,27970.0,221256.0,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,127631,38.100000000000001,65886.0,36038.0,1557873.0,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,66653,37.700000000000003,56303.0,29777.0,867996.0,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,31398,38.200000000000003,60523.0,32176.0,348122.0,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,29652,36.700000000000003,59597.0,31814.0,337739.0,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,44452,38.899999999999999,50589.0,28178.0,747010.0,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362,36.899999999999999,49469.0,27923.0,871467.0,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492,44.700000000000003,57918.0,32637.0,153131.0,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,18848,38.700000000000003,84805.0,42122.0,539991.0,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,68553,39.5,81215.0,43761.0,680962.0,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265,39.700000000000003,57144.0,31713.0,1398527.0,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378,38.0,71306.0,37625.0,526065.0,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418,37.5,45081.0,24369.0,585786.0,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,649,38.600000000000001,55461.0,30810.0,810045.0,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,649,39.899999999999999,54970.0,31151.0,134605.0,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571,36.5,61439.0,32302.0,206579.0,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382,38.0,60365.0,31557.0,384690.0,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124,42.899999999999999,76768.0,40003.0,98682.0,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,88783,39.899999999999999,82545.0,42745.0,869081.0,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,92454,37.799999999999997,49754.0,27230.0,392065.0,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,264876,38.700000000000003,54602.0,30783.0,1467591.0,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717,35.100000000000001,64894.0,36062.0,78198.0,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319,38.799999999999997,68486.0,39326.0,2681277.0,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397,39.399999999999999,56602.0,31552.0,1588343.0,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,39328,36.600000000000001,52919.0,28422.0,598373.0,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,41293,39.299999999999997,62818.0,33763.0,533527.0,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,127915,40.799999999999997,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,57231,39.899999999999999,67167.0,36121.0,125826.0,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,6,39.399999999999999,53199.0,29426.0,741650.0,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,8638,37.0,58275.0,30773.0,110553.0,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,69356,38.700000000000003,53320.0,29859.0,996930.0,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,282856,34.600000000000001,61874.0,31277.0,4072194.0,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,96848,30.800000000000001,71621.0,29775.0,298537.0,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313,42.899999999999999,61973.0,34577.0,65652.0,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463,38.200000000000003,74222.0,39278.0,865691.0,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,747,37.700000000000003,73775.0,38915.0,785244.0,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,18175,42.5,46711.0,26480.0,310044.0,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,57716,39.5,61747.0,33375.0,639160.0,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,5824,37.700000000000003,64049.0,33366.0,62257.0,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [18]:
master_geojson["Median Age"] = master_geojson["Median Age"].str.split(".")
master_geojson

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,48762,"[39, 0]",50536.0,27928.0,795989.0,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,7368,"[34, 299999999999997]",77640.0,36787.0,76933.0,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,299,"[37, 700000000000003]",58945.0,30694.0,1043764.0,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,29993,"[38, 100000000000001]",47597.0,26577.0,496260.0,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497,"[36, 5]",75235.0,36955.0,5149742.0,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,56349,"[36, 700000000000003]",72331.0,38226.0,565873.0,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,35774,"[41, 0]",78444.0,44496.0,344146.0,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248,"[40, 600000000000001]",68287.0,35450.0,109400.0,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,14294,"[39, 100000000000001]",81275.0,35567.0,130649.0,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,1636,"[42, 0]",55660.0,31619.0,2870487.0,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,3847,"[36, 700000000000003]",58700.0,31067.0,1528558.0,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,17177,"[36, 399999999999999]",55785.0,27970.0,221256.0,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,127631,"[38, 100000000000001]",65886.0,36038.0,1557873.0,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,66653,"[37, 700000000000003]",56303.0,29777.0,867996.0,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,31398,"[38, 200000000000003]",60523.0,32176.0,348122.0,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,29652,"[36, 700000000000003]",59597.0,31814.0,337739.0,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,44452,"[38, 899999999999999]",50589.0,28178.0,747010.0,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362,"[36, 899999999999999]",49469.0,27923.0,871467.0,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492,"[44, 700000000000003]",57918.0,32637.0,153131.0,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,18848,"[38, 700000000000003]",84805.0,42122.0,539991.0,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,68553,"[39, 5]",81215.0,43761.0,680962.0,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265,"[39, 700000000000003]",57144.0,31713.0,1398527.0,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378,"[38, 0]",71306.0,37625.0,526065.0,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418,"[37, 5]",45081.0,24369.0,585786.0,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,649,"[38, 600000000000001]",55461.0,30810.0,810045.0,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,649,"[39, 899999999999999]",54970.0,31151.0,134605.0,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571,"[36, 5]",61439.0,32302.0,206579.0,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382,"[38, 0]",60365.0,31557.0,384690.0,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124,"[42, 899999999999999]",76768.0,40003.0,98682.0,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,88783,"[39, 899999999999999]",82545.0,42745.0,869081.0,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,92454,"[37, 799999999999997]",49754.0,27230.0,392065.0,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,264876,"[38, 700000000000003]",54602.0,30783.0,1467591.0,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717,"[35, 100000000000001]",64894.0,36062.0,78198.0,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319,"[38, 799999999999997]",68486.0,39326.0,2681277.0,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397,"[39, 399999999999999]",56602.0,31552.0,1588343.0,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,39328,"[36, 600000000000001]",52919.0,28422.0,598373.0,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,41293,"[39, 299999999999997]",62818.0,33763.0,533527.0,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,127915,"[40, 799999999999997]",61744.0,34352.0,1539183.0,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,57231,"[39, 899999999999999]",67167.0,36121.0,125826.0,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,6,"[39, 399999999999999]",53199.0,29426.0,741650.0,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,8638,"[37, 0]",58275.0,30773.0,110553.0,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,69356,"[38, 700000000000003]",53320.0,29859.0,996930.0,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,282856,"[34, 600000000000001]",61874.0,31277.0,4072194.0,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,96848,"[30, 800000000000001]",71621.0,29775.0,298537.0,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313,"[42, 899999999999999]",61973.0,34577.0,65652.0,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463,"[38, 200000000000003]",74222.0,39278.0,865691.0,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,747,"[37, 700000000000003]",73775.0,38915.0,785244.0,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,18175,"[42, 5]",46711.0,26480.0,310044.0,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,57716,"[39, 5]",61747.0,33375.0,639160.0,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,5824,"[37, 700000000000003]",64049.0,33366.0,62257.0,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [19]:
master_geojson["Median Age"] = master_geojson["Median Age"].str.get(0)

master_geojson

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,48762,39,50536.0,27928.0,795989.0,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,7368,34,77640.0,36787.0,76933.0,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,299,37,58945.0,30694.0,1043764.0,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,29993,38,47597.0,26577.0,496260.0,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497,36,75235.0,36955.0,5149742.0,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,56349,36,72331.0,38226.0,565873.0,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,35774,41,78444.0,44496.0,344146.0,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248,40,68287.0,35450.0,109400.0,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,14294,39,81275.0,35567.0,130649.0,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,1636,42,55660.0,31619.0,2870487.0,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,3847,36,58700.0,31067.0,1528558.0,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,17177,36,55785.0,27970.0,221256.0,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,127631,38,65886.0,36038.0,1557873.0,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,66653,37,56303.0,29777.0,867996.0,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,31398,38,60523.0,32176.0,348122.0,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,29652,36,59597.0,31814.0,337739.0,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,44452,38,50589.0,28178.0,747010.0,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362,36,49469.0,27923.0,871467.0,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492,44,57918.0,32637.0,153131.0,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,18848,38,84805.0,42122.0,539991.0,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,68553,39,81215.0,43761.0,680962.0,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265,39,57144.0,31713.0,1398527.0,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378,38,71306.0,37625.0,526065.0,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418,37,45081.0,24369.0,585786.0,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,649,38,55461.0,30810.0,810045.0,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,649,39,54970.0,31151.0,134605.0,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571,36,61439.0,32302.0,206579.0,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382,38,60365.0,31557.0,384690.0,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124,42,76768.0,40003.0,98682.0,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,88783,39,82545.0,42745.0,869081.0,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,92454,37,49754.0,27230.0,392065.0,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,264876,38,54602.0,30783.0,1467591.0,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717,35,64894.0,36062.0,78198.0,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319,38,68486.0,39326.0,2681277.0,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397,39,56602.0,31552.0,1588343.0,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,39328,36,52919.0,28422.0,598373.0,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,41293,39,62818.0,33763.0,533527.0,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,127915,40,61744.0,34352.0,1539183.0,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,57231,39,67167.0,36121.0,125826.0,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,6,39,53199.0,29426.0,741650.0,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,8638,37,58275.0,30773.0,110553.0,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,69356,38,53320.0,29859.0,996930.0,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,282856,34,61874.0,31277.0,4072194.0,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,96848,30,71621.0,29775.0,298537.0,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313,42,61973.0,34577.0,65652.0,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463,38,74222.0,39278.0,865691.0,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,747,37,73775.0,38915.0,785244.0,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,18175,42,46711.0,26480.0,310044.0,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,57716,39,61747.0,33375.0,639160.0,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,5824,37,64049.0,33366.0,62257.0,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [20]:
master_geojson["Household Income"] = master_geojson["Household Income"].str.replace(".0", "")
master_geojson["Per Capita Income"] = master_geojson["Per Capita Income"].str.replace(".0", "")
master_geojson["Poverty Count"] = master_geojson["Poverty Count"].str.replace(".0", "")
master_geojson

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,48762,39,536,27928,795989,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,7368,34,776,36787,76933,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,299,37,58945,694,43764,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,29993,38,47597,26577,4962,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497,36,75235,36955,5149742,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,56349,36,72331,38226,565873,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,35774,41,78444,44496,344146,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248,40,68287,354,90,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,14294,39,81275,35567,1649,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,1636,42,556,31619,28487,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,3847,36,580,367,1528558,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,17177,36,55785,279,221256,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,127631,38,65886,338,1557873,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,66653,37,563,29777,867996,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,31398,38,523,32176,348122,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,29652,36,59597,31814,337739,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,44452,38,589,28178,74,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362,36,49469,27923,871467,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492,44,57918,32637,153131,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,18848,38,845,42122,539991,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,68553,39,81215,43761,6962,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265,39,57144,31713,1398527,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378,38,716,37625,5265,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418,37,481,24369,585786,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,649,38,55461,8,8045,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,649,39,549,31151,1345,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571,36,61439,322,6579,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382,38,365,31557,3846,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124,42,76768,3,98682,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,88783,39,82545,42745,8681,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,92454,37,49754,272,3965,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,264876,38,542,783,1467591,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717,35,64894,362,78198,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319,38,68486,39326,2681277,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397,39,562,31552,1588343,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,39328,36,52919,28422,598373,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,41293,39,62818,33763,533527,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,127915,40,61744,34352,1539183,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,57231,39,67167,36121,125826,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,6,39,53199,29426,7416,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,8638,37,58275,773,1553,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,69356,38,533,29859,9969,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,282856,34,61874,31277,72194,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,96848,30,71621,29775,298537,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313,42,61973,34577,65652,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463,38,74222,39278,865691,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,747,37,73775,38915,785244,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,18175,42,46711,264,3044,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,57716,39,61747,33375,6391,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,5824,37,649,33366,62257,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [21]:
master_geojson["Population"] = master_geojson["Population"].astype(int)

In [22]:
master_geojson["Median Age"] = master_geojson["Median Age"].astype(int)
master_geojson["Household Income"] = master_geojson["Household Income"].astype(int)
master_geojson["Per Capita Income"] = master_geojson["Per Capita Income"].astype(int)
master_geojson["Poverty Count"] = master_geojson["Poverty Count"].astype(int)

In [23]:
master_geojson.dtypes

average high           object
average low            object
average rain           object
Capital                object
State                   int64
Population              int64
Median Age              int64
Household Income        int64
Per Capita Income       int64
Poverty Count           int64
Poverty Rate          float64
state                  object
id                     object
density               float64
geometry             geometry
dtype: object

In [24]:
master_geojson

,average high,average low,average rain,Capital,State,Population,Median Age,Household Income,Per Capita Income,Poverty Count,Poverty Rate,state,id,density,geometry
0,"{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr':...","{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr':...",montgomery,1,48762,39,536,27928,795989,16.323794,Alabama,01,94.650,"POLYGON ((-87.359 35.001, -85.607 34.985, -85...."
1,"{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr':...","{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr':...","{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr':...",juneau,2,7368,34,776,36787,76933,10.437707,Alaska,02,1.264,"MULTIPOLYGON (((-131.602 55.118, -131.569 55.2..."
2,"{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr':...","{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr':...","{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2....",phoenix,4,299,37,58945,694,43764,14.804535,Arizona,04,57.050,"POLYGON ((-109.043 37.000, -109.048 31.332, -1..."
3,"{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr':...","{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11...",little_rock,5,29993,38,47597,26577,4962,16.545475,Arkansas,05,56.430,"POLYGON ((-94.474 36.502, -90.153 36.496, -90...."
4,"{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr':...","{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr':...","{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr':...",sacramento,6,39283497,36,75235,36955,5149742,13.109174,California,06,241.700,"POLYGON ((-123.233 42.006, -122.379 42.012, -1..."
5,"{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, ...",denver,8,56349,36,72331,38226,565873,10.086235,Colorado,08,49.330,"POLYGON ((-107.920 41.004, -105.729 40.998, -1..."
6,"{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr':...","{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr':...","{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr':...",hartford,9,35774,41,78444,44496,344146,9.626262,Connecticut,09,739.100,"POLYGON ((-73.054 42.039, -71.799 42.023, -71...."
7,"{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr':...","{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr':...","{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr':...",dover,10,957248,40,68287,354,90,11.428595,Delaware,10,464.300,"POLYGON ((-75.414 39.804, -75.507 39.684, -75...."
8,"{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr':...","{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr':...","{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",honolulu,15,14294,39,81275,35567,1649,9.187086,Florida,12,353.400,"POLYGON ((-85.497 30.998, -85.004 31.003, -84...."
9,"{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr':...","{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr':...","{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr':...",tallahassee,12,1636,42,556,31619,28487,13.733313,Georgia,13,169.500,"POLYGON ((-83.109 35.001, -83.323 34.788, -83...."
10,"{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr':...","{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr':...","{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7...",atlanta,13,3847,36,580,367,1528558,14.692238,Hawaii,15,214.100,"MULTIPOLYGON (((-155.635 18.948, -155.881 19.0..."
11,"{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",boise,16,17177,36,55785,279,221256,12.880571,Idaho,16,19.150,"POLYGON ((-116.048 49.000, -116.048 47.976, -1..."
12,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr':...","{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr':...",springfield,17,127631,38,65886,338,1557873,12.198873,Illinois,17,231.500,"POLYGON ((-90.640 42.510, -88.789 42.494, -87...."
13,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr':...",indianapolis,18,66653,37,563,29777,867996,13.021822,Indiana,18,181.700,"POLYGON ((-85.990 41.760, -84.807 41.760, -84...."
14,"{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr':...","{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr':...","{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11...",des_moines,19,31398,38,523,32176,348122,11.088425,Iowa,19,54.810,"POLYGON ((-91.368 43.501, -91.215 43.501, -91...."
15,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr':...","{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr':...",topeka,20,29652,36,59597,31814,337739,11.603551,Kansas,20,35.090,"POLYGON ((-101.906 40.002, -95.306 40.002, -95..."
16,"{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr':...","{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr':...","{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr':...",frankfort,21,44452,38,589,28178,74,16.790318,Kentucky,21,110.000,"POLYGON ((-83.903 38.769, -83.679 38.632, -83...."
17,"{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr':...","{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr':...","{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr':...",baton_rouge,22,4664362,36,49469,27923,871467,18.683520,Louisiana,22,105.000,"POLYGON ((-93.608 33.019, -91.166 33.002, -91...."
18,"{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr':...","{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr':...",augusta,23,1335492,44,57918,32637,153131,11.466261,Maine,23,43.040,"POLYGON ((-70.704 43.058, -70.824 43.129, -70...."
19,"{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr':...","{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr':...",annapolis,24,18848,38,845,42122,539991,8.971667,Maryland,24,596.300,"MULTIPOLYGON (((-75.995 37.953, -76.017 37.953..."
20,"{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",boston,25,68553,39,81215,43761,6962,9.940249,Massachusetts,25,840.200,"POLYGON ((-70.918 42.888, -70.819 42.872, -70...."
21,"{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr':...","{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr':...","{'jan': 1.65, 'feb': 1.47, 'mar': 2.06, 'apr':...",lansing,26,9965265,39,57144,31713,1398527,14.034017,Michigan,26,173.900,"MULTIPOLYGON (((-83.454 41.732, -84.807 41.694..."
22,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': ...","{'jan': 0.77, 'feb': 0.67, 'mar': 1.55, 'apr':...",saint_paul,27,5563378,38,716,37625,5265,9.455856,Minnesota,27,67.140,"POLYGON ((-92.015 46.705, -92.091 46.749, -92...."
23,"{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr':...","{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr':...","{'jan': 4.97, 'feb': 4.76, 'mar': 5.04, 'apr':...",jackson,28,2984418,37,481,24369,585786,19.628149,Mississippi,28,63.500,"POLYGON ((-88.471 34.996, -88.203 34.996, -88...."
24,"{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr':...","{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 1.9, 'feb': 2.31, 'mar': 3.0, 'apr': 4...",jefferson_city,29,649,38,55461,8,8045,13.268746,Missouri,29,87.260,"POLYGON ((-91.834 40.610, -91.730 40.615, -91...."
25,"{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr':...","{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr':...","{'jan': 0.36, 'feb': 0.3, 'mar': 0.59, 'apr': ...",helena,30,649,39,549,31151,1345,12.811605,Montana,30,6.858,"POLYGON ((-104.048 49.000, -104.042 47.861, -1..."
26,"{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr':...","{'jan': 0.64, 'feb': 0.77, 'mar': 1.93, 'apr':...",lincoln,31,1914571,36,61439,322,6579,10.789832,Nebraska,31,23.970,"POLYGON ((-103.325 43.003, -101.627 42.998, -9..."
27,"{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr':...","{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr':...","{'jan': 1.56, 'feb': 1.57, 'mar': 1.12, 'apr':...",carson_city,32,2972382,38,365,31557,3846,12.942145,Nevada,32,24.800,"POLYGON ((-117.028 42.001, -114.043 41.995, -1..."
28,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr':...","{'jan': 2.7, 'feb': 2.62, 'mar': 3.27, 'apr': ...",concord,33,1348124,42,76768,3,98682,7.319950,New Hampshire,33,147.000,"POLYGON ((-71.082 45.303, -71.033 44.657, -70...."
29,"{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr':...","{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr':...","{'jan': 1.03, 'feb': 1.7, 'mar': 2.66, 'apr': ...",trenton,34,88783,39,82545,42745,8681,9.788598,New Jersey,34,1189.000,"POLYGON ((-74.237 41.141, -73.902 40.998, -74...."
30,"{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr':...","{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr':...","{'jan': 0.6, 'feb': 0.53, 'mar': 0.94, 'apr': ...",santa_fe,35,92454,37,49754,272,3965,18.737091,New Mexico,35,17.160,"POLYGON ((-107.421 37.000, -106.868 36.995, -1..."
31,"{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr':...","{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr':...","{'jan': 4.45, 'feb': 3.58, 'mar': 4.45, 'apr':...",raleigh,37,264876,38,542,783,1467591,14.297211,New York,36,412.300,"POLYGON ((-73.344 45.013, -73.333 44.805, -73...."
32,"{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr':...","{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 3...","{'jan': 0.43, 'feb': 0.51, 'mar': 0.87, 'apr':...",bismarck,38,756717,35,64894,362,78198,10.333850,North Carolina,37,198.200,"POLYGON ((-80.979 36.562, -80.294 36.546, -79...."
33,"{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr':...","{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr':...","{'jan': 2.59, 'feb': 2.2, 'mar': 3.21, 'apr': ...",albany,36,19572319,38,68486,39326,2681277,13.699332,North Dakota,38,9.916,"POLYGON ((-97.229 49.000, -97.097 48.683, -97...."
34,"{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr':...","{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr':...","{'jan': 13.0, 'feb': 11.0, 'mar': 13.0, 'apr':...",columbus,39,11655397,39,562,31552,1588343,13.627532,Ohio,39,281.900,"POLYGON ((-80.519 41.979, -80.519 40.637, -80...."
35,"{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr':...","{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr':...","{'jan': 1.39, 'feb': 1.58, 'mar': 3.06, 'apr':...",oklahoma_city,40,39328,36,52919,28422,598373,15.214665,Oklahoma,40,55.220,"POLYGON ((-100.088 37.000, -94.616 37.000, -94..."
36,"{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr':...","{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr':...","{'jan': 5.96, 'feb': 4.56, 'mar': 3.99, 'apr':...",salem,41,41293,39,62818,33763,533527,12.918946,Oregon,41,40.330,"POLYGON ((-123.211 46.174, -123.118 46.185, -1..."
37,"{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr':...","{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr':...","{'jan': 3.19, 'feb': 2.87, 'mar': 3.58, 'apr':...",harrisburg,42,127915,40,61744,34352,1539183,12.032830,Pennsylvania,42,284.300,"POLYGON ((-79.763 42.253, -79.763 42.001, -75...."
38,"{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr':...","{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr':...","{'jan': 11.0, 'feb': 9.0, 'mar': 11.0, 'apr': ...",providence,44,57231,39,67167,36121,125826,11.901467,Rhode Island,44,1006.000,"MULTIPOLYGON (((-71.197 41.678, -71.120 41.497..."
39,"{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr':...","{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr':...","{'jan': 3.85, 'feb': 3.77, 'mar': 4.21, 'apr':...",columbia,45,6,39,53199,29426,7416,14.771533,South Carolina,45,155.400,"POLYGON ((-82.764 35.067, -82.551 35.160, -82...."
40,"{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr':...","{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr':...","{'jan': 0.42, 'feb': 0.59, 'mar': 1.21, 'apr':...",pierre,46,8638,37,58275,773,1553,12.697930,South Dakota,46,98.070,"POLYGON ((-104.048 45.944, -96.561 45.933, -96..."
41,"{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr':...","{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr':...","{'jan': 12.0, 'feb': 11.0, 'mar': 12.0, 'apr':...",nashville,47,69356,38,533,29859,9969,14.858803,Tennessee,47,88.080,"POLYGON ((-88.055 36.496, -88.071 36.677, -87...."
42,"{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr':...","{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr':...","{'jan': 2.22, 'feb': 2.02, 'mar': 2.76, 'apr':...",austin,48,282856,34,61874,31277,72194,14.409309,Texas,48,98.070,"POLYGON ((-101.813 36.502, -100.000 36.502, -1..."
43,"{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr':...","{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr':...","{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': ...",salt_lake_city,49,96848,30,71621,29775,298537,9.640028,Utah,49,34.300,"POLYGON ((-112.164 41.995, -111.047 42.001, -1..."
44,"{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr':...","{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': ...","{'jan': 2.45, 'feb': 2.04, 'mar': 2.39, 'apr':...",montpelier,50,624313,42,61973,34577,65652,10.515879,Vermont,50,67.730,"POLYGON ((-71.504 45.013, -71.493 44.914, -71...."
45,"{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr':...","{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr':...","{'jan': 9.0, 'feb': 8.0, 'mar': 10.0, 'apr': 1...",richmond,51,8454463,38,74222,39278,865691,10.239456,Virginia,51,204.500,"MULTIPOLYGON (((-75.398 38.013, -75.244 38.030..."
46,"{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr':...","{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr':...","{'jan': 7.84, 'feb': 5.27, 'mar': 5.29, 'apr':...",olympia,53,747,37,73775,38915,785244,10.605519,Washington,53,102.600,"MULTIPOLYGON (((-117.033 49.000, -117.044 47.7..."
47,"{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr':...","{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr':...","{'jan': 3.0, 'feb': 3.19, 'mar': 3.91, 'apr': ...",charleston,54,18175,42,46711,264,3044,17.060647,West Virginia,54,77.060,"POLYGON ((-80.519 40.637, -80.519 39.722, -79...."
48,"{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr':...","{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr':...","{'jan': 1.23, 'feb': 1.45, 'mar': 2.2, 'apr': ...",madison,55,57716,39,61747,33375,6391,11.037668,Wisconsin,55,105.200,"POLYGON ((-90.415 46.568, -90.229 46.508, -90...."
49,"{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr':...","{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr':...","{'jan': 4.0, 'feb': 6.0, 'mar': 8.0, 'apr': 10...",cheyenne,56,5824,37,649,33366,62257,10.715048,Wyoming,56,5.851,"POLYGON ((-109.081 45.002, -105.915 45.002, -1..."

In [ ]:
# Saving to CSV
# master_geojson.to_csv("../../resources/data/completedata_for_geojson.csv", index=False)

In [25]:
import json

In [38]:
i = master_geojson.to_dict()
i

{'average high': {0: "{'jan': 57.0, 'feb': 62.0, 'mar': 70.0, 'apr': 77.0, 'may': 84.0, 'jun': 90.0, 'jul': 92.0, 'aug': 92.0, 'sep': 87.0, 'oct': 78.0, 'nov': 69.0, 'dec': 60.0}",
  1: "{'jan': 33.0, 'feb': 35.0, 'mar': 40.0, 'apr': 48.0, 'may': 57.0, 'jun': 62.0, 'jul': 64.0, 'aug': 63.0, 'sep': 56.0, 'oct': 47.0, 'nov': 38.0, 'dec': 34.0}",
  2: "{'jan': 67.0, 'feb': 71.0, 'mar': 77.0, 'apr': 85.0, 'may': 95.0, 'jun': 104.0, 'jul': 106.0, 'aug': 104.0, 'sep': 100.0, 'oct': 89.0, 'nov': 76.0, 'dec': 66.0}",
  3: "{'jan': 51.0, 'feb': 55.0, 'mar': 64.0, 'apr': 73.0, 'may': 81.0, 'jun': 89.0, 'jul': 92.0, 'aug': 93.0, 'sep': 86.0, 'oct': 75.0, 'nov': 63.0, 'dec': 52.0}",
  4: "{'jan': 54.0, 'feb': 60.0, 'mar': 65.0, 'apr': 71.0, 'may': 80.0, 'jun': 87.0, 'jul': 92.0, 'aug': 91.0, 'sep': 87.0, 'oct': 78.0, 'nov': 64.0, 'dec': 54.0}",
  5: "{'jan': 45.0, 'feb': 46.0, 'mar': 54.0, 'apr': 61.0, 'may': 72.0, 'jun': 82.0, 'jul': 90.0, 'aug': 88.0, 'sep': 79.0, 'oct': 66.0, 'nov': 52.0, 'dec': 45.0}",
  6: "{'jan': 35.0, 'feb': 38.0, 'mar': 47.0, 'apr': 58.0, 'may': 70.0, 'jun': 79.0, 'jul': 84.0, 'aug': 82.0, 'sep': 74.0, 'oct': 63.0, 'nov': 51.0, 'dec': 40.0}",
  7: "{'jan': 43.0, 'feb': 47.0, 'mar': 55.0, 'apr': 66.0, 'may': 75.0, 'jun': 83.0, 'jul': 87.0, 'aug': 85.0, 'sep': 79.0, 'oct': 69.0, 'nov': 58.0, 'dec': 47.0}",
  8: "{'jan': 80.0, 'feb': 80.0, 'mar': 81.0, 'apr': 83.0, 'may': 85.0, 'jun': 87.0, 'jul': 88.0, 'aug': 89.0, 'sep': 89.0, 'oct': 87.0, 'nov': 84.0, 'dec': 81.0}",
  9: "{'jan': 64.0, 'feb': 67.0, 'mar': 74.0, 'apr': 80.0, 'may': 87.0, 'jun': 91.0, 'jul': 92.0, 'aug': 92.0, 'sep': 88.0, 'oct': 81.0, 'nov': 73.0, 'dec': 65.0}",
  10: "{'jan': 61.0, 'feb': 52.0, 'mar': 72.0, 'apr': 82.0, 'may': 86.0, 'jun': 87.0, 'jul': 86.0, 'aug': 79.0, 'sep': 71.0, 'oct': 54.0, 'nov': 62.0, 'dec': 51.0}",
  11: "{'jan': 38.0, 'feb': 45.0, 'mar': 55.0, 'apr': 62.0, 'may': 72.0, 'jun': 81.0, 'jul': 91.0, 'aug': 90.0, 'sep': 79.0, 'oct': 65.0, 'nov': 48.0, 'dec': 38.0}",
  12: "{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr': 65.0, 'may': 75.0, 'jun': 83.0, 'jul': 86.0, 'aug': 85.0, 'sep': 79.0, 'oct': 66.0, 'nov': 52.0, 'dec': 38.0}",
  13: "{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr': 63.0, 'may': 73.0, 'jun': 82.0, 'jul': 85.0, 'aug': 84.0, 'sep': 78.0, 'oct': 65.0, 'nov': 52.0, 'dec': 39.0}",
  14: "{'jan': 31.0, 'feb': 36.0, 'mar': 49.0, 'apr': 62.0, 'may': 72.0, 'jun': 82.0, 'jul': 86.0, 'aug': 84.0, 'sep': 76.0, 'oct': 63.0, 'nov': 48.0, 'dec': 34.0}",
  15: "{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr': 67.0, 'may': 76.0, 'jun': 85.0, 'jul': 89.0, 'aug': 89.0, 'sep': 80.0, 'oct': 68.0, 'nov': 55.0, 'dec': 42.0}",
  16: "{'jan': 40.0, 'feb': 45.0, 'mar': 55.0, 'apr': 66.0, 'may': 75.0, 'jun': 83.0, 'jul': 87.0, 'aug': 86.0, 'sep': 79.0, 'oct': 68.0, 'nov': 55.0, 'dec': 44.0}",
  17: "{'jan': 62.0, 'feb': 66.0, 'mar': 73.0, 'apr': 79.0, 'may': 86.0, 'jun': 91.0, 'jul': 92.0, 'aug': 92.0, 'sep': 89.0, 'oct': 81.0, 'nov': 72.0, 'dec': 64.0}",
  18: "{'jan': 28.0, 'feb': 32.0, 'mar': 40.0, 'apr': 53.0, 'may': 65.0, 'jun': 74.0, 'jul': 79.0, 'aug': 78.0, 'sep': 70.0, 'oct': 57.0, 'nov': 45.0, 'dec': 33.0}",
  19: "{'jan': 44.0, 'feb': 48.0, 'mar': 57.0, 'apr': 68.0, 'may': 77.0, 'jun': 86.0, 'jul': 89.0, 'aug': 87.0, 'sep': 81.0, 'oct': 69.0, 'nov': 59.0, 'dec': 48.0}",
  20: "{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr': 56.0, 'may': 66.0, 'jun': 76.0, 'jul': 81.0, 'aug': 80.0, 'sep': 72.0, 'oct': 61.0, 'nov': 51.0, 'dec': 41.0}",
  21: "{'jan': 30.0, 'feb': 33.0, 'mar': 44.0, 'apr': 58.0, 'may': 69.0, 'jun': 78.0, 'jul': 82.0, 'aug': 80.0, 'sep': 73.0, 'oct': 60.0, 'nov': 47.0, 'dec': 34.0}",
  22: "{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr': 58.0, 'may': 71.0, 'jun': 80.0, 'jul': 85.0, 'aug': 82.0, 'sep': 73.0, 'oct': 59.0, 'nov': 42.0, 'dec': 29.0}",
  23: "{'jan': 56.0, 'feb': 60.0, 'mar': 69.0, 'apr': 76.0, 'may': 83.0, 'jun': 89.0, 'jul': 92.0, 'aug': 92.0, 'sep': 87.0, 'oct': 77.0, 'nov': 67.0, 'dec': 58.0}",
  24: "{'jan': 40.0, 'feb': 45.0, 'mar': 56.0, 'apr': 67.0, 'may': 75.0, 'jun': 83.0, 'jul': 88.0, 'aug': 88.0, 'sep': 80.0, 'oct': 69.0, 'nov': 56.0, 'dec': 43.0}",
  25: "{'jan': 33.0, 'feb': 39.0, 'mar': 48.0, 'apr': 58.0, 'may': 67.0, 'jun': 76.0, 'jul': 86.0, 'aug': 85.0, 'sep': 73.0, 'oct': 59.0, 'nov': 43.0, 'dec': 32.0}",
  26: "{'jan': 35.0, 'feb': 40.0, 'mar': 52.0, 'apr': 64.0, 'may': 74.0, 'jun': 84.0, 'jul': 89.0, 'aug': 87.0, 'sep': 79.0, 'oct': 66.0, 'nov': 50.0, 'dec': 37.0}",
  27: "{'jan': 45.0, 'feb': 50.0, 'mar': 57.0, 'apr': 63.0, 'may': 71.0, 'jun': 81.0, 'jul': 90.0, 'aug': 88.0, 'sep': 80.0, 'oct': 68.0, 'nov': 54.0, 'dec': 45.0}",
  28: "{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr': 57.0, 'may': 69.0, 'jun': 77.0, 'jul': 82.0, 'aug': 81.0, 'sep': 73.0, 'oct': 60.0, 'nov': 48.0, 'dec': 36.0}",
  29: "{'jan': 35.0, 'feb': 41.0, 'mar': 52.0, 'apr': 64.0, 'may': 74.0, 'jun': 83.0, 'jul': 88.0, 'aug': 87.0, 'sep': 78.0, 'oct': 66.0, 'nov': 51.0, 'dec': 38.0}",
  30: "{'jan': 44.0, 'feb': 48.0, 'mar': 56.0, 'apr': 65.0, 'may': 74.0, 'jun': 83.0, 'jul': 86.0, 'aug': 83.0, 'sep': 78.0, 'oct': 67.0, 'nov': 53.0, 'dec': 43.0}",
  31: "{'jan': 51.0, 'feb': 56.0, 'mar': 64.0, 'apr': 73.0, 'may': 79.0, 'jun': 86.0, 'jul': 89.0, 'aug': 87.0, 'sep': 82.0, 'oct': 72.0, 'nov': 63.0, 'dec': 54.0}",
  32: "{'jan': 23.0, 'feb': 28.0, 'mar': 40.0, 'apr': 57.0, 'may': 68.0, 'jun': 77.0, 'jul': 85.0, 'aug': 83.0, 'sep': 72.0, 'oct': 58.0, 'nov': 40.0, 'dec': 26.0}",
  33: "{'jan': 31.0, 'feb': 35.0, 'mar': 44.0, 'apr': 58.0, 'may': 69.0, 'jun': 78.0, 'jul': 82.0, 'aug': 80.0, 'sep': 72.0, 'oct': 60.0, 'nov': 48.0, 'dec': 36.0}",
  34: "{'jan': 36.0, 'feb': 40.0, 'mar': 52.0, 'apr': 63.0, 'may': 73.0, 'jun': 82.0, 'jul': 85.0, 'aug': 84.0, 'sep': 77.0, 'oct': 65.0, 'nov': 52.0, 'dec': 41.0}",
  35: "{'jan': 50.0, 'feb': 55.0, 'mar': 63.0, 'apr': 72.0, 'may': 80.0, 'jun': 88.0, 'jul': 94.0, 'aug': 93.0, 'sep': 85.0, 'oct': 73.0, 'nov': 62.0, 'dec': 51.0}",
  36: "{'jan': 48.0, 'feb': 52.0, 'mar': 56.0, 'apr': 61.0, 'may': 68.0, 'jun': 74.0, 'jul': 82.0, 'aug': 82.0, 'sep': 77.0, 'oct': 64.0, 'nov': 53.0, 'dec': 46.0}",
  37: "{'jan': 38.0, 'feb': 41.0, 'mar': 51.0, 'apr': 63.0, 'may': 73.0, 'jun': 81.0, 'jul': 86.0, 'aug': 84.0, 'sep': 76.0, 'oct': 64.0, 'nov': 53.0, 'dec': 42.0}",
  38: "{'jan': 37.0, 'feb': 40.0, 'mar': 48.0, 'apr': 59.0, 'may': 68.0, 'jun': 78.0, 'jul': 83.0, 'aug': 81.0, 'sep': 74.0, 'oct': 63.0, 'nov': 53.0, 'dec': 42.0}",
  39: "{'jan': 58.0, 'feb': 63.0, 'mar': 71.0, 'apr': 80.0, 'may': 87.0, 'jun': 92.0, 'jul': 95.0, 'aug': 93.0, 'sep': 88.0, 'oct': 78.0, 'nov': 69.0, 'dec': 60.0}",
  40: "{'jan': 30.0, 'feb': 35.0, 'mar': 45.0, 'apr': 60.0, 'may': 70.0, 'jun': 80.0, 'jul': 89.0, 'aug': 87.0, 'sep': 76.0, 'oct': 61.0, 'nov': 44.0, 'dec': 31.0}",
  41: "{'jan': 47.0, 'feb': 52.0, 'mar': 61.0, 'apr': 71.0, 'may': 78.0, 'jun': 86.0, 'jul': 89.0, 'aug': 89.0, 'sep': 82.0, 'oct': 72.0, 'nov': 60.0, 'dec': 49.0}",
  42: "{'jan': 62.0, 'feb': 65.0, 'mar': 72.0, 'apr': 80.0, 'may': 87.0, 'jun': 92.0, 'jul': 96.0, 'aug': 97.0, 'sep': 91.0, 'oct': 82.0, 'nov': 71.0, 'dec': 63.0}",
  43: "{'jan': 38.0, 'feb': 44.0, 'mar': 53.0, 'apr': 61.0, 'may': 71.0, 'jun': 82.0, 'jul': 90.0, 'aug': 89.0, 'sep': 78.0, 'oct': 65.0, 'nov': 50.0, 'dec': 40.0}",
  44: "{'jan': 26.0, 'feb': 30.0, 'mar': 39.0, 'apr': 53.0, 'may': 66.0, 'jun': 74.0, 'jul': 78.0, 'aug': 77.0, 'sep': 69.0, 'oct': 56.0, 'nov': 44.0, 'dec': 32.0}",
  45: "{'jan': 47.0, 'feb': 51.0, 'mar': 60.0, 'apr': 70.0, 'may': 78.0, 'jun': 86.0, 'jul': 90.0, 'aug': 88.0, 'sep': 81.0, 'oct': 71.0, 'nov': 61.0, 'dec': 51.0}",
  46: "{'jan': 46.0, 'feb': 49.0, 'mar': 54.0, 'apr': 59.0, 'may': 65.0, 'jun': 71.0, 'jul': 77.0, 'aug': 78.0, 'sep': 72.0, 'oct': 60.0, 'nov': 50.0, 'dec': 44.0}",
  47: "{'jan': 42.0, 'feb': 47.0, 'mar': 56.0, 'apr': 68.0, 'may': 75.0, 'jun': 82.0, 'jul': 85.0, 'aug': 84.0, 'sep': 78.0, 'oct': 68.0, 'nov': 57.0, 'dec': 46.0}",
  48: "{'jan': 26.0, 'feb': 31.0, 'mar': 43.0, 'apr': 57.0, 'may': 68.0, 'jun': 78.0, 'jul': 82.0, 'aug': 79.0, 'sep': 72.0, 'oct': 59.0, 'nov': 44.0, 'dec': 30.0}",
  49: "{'jan': 40.0, 'feb': 40.0, 'mar': 47.0, 'apr': 55.0, 'may': 65.0, 'jun': 75.0, 'jul': 83.0, 'aug': 81.0, 'sep': 72.0, 'oct': 59.0, 'nov': 47.0, 'dec': 38.0}"},
 'average low': {0: "{'jan': 36.0, 'feb': 39.0, 'mar': 45.0, 'apr': 52.0, 'may': 61.0, 'jun': 68.0, 'jul': 71.0, 'aug': 71.0, 'sep': 65.0, 'oct': 53.0, 'nov': 44.0, 'dec': 37.0}",
  1: "{'jan': 24.0, 'feb': 25.0, 'mar': 28.0, 'apr': 33.0, 'may': 41.0, 'jun': 47.0, 'jul': 50.0, 'aug': 49.0, 'sep': 44.0, 'oct': 38.0, 'nov': 29.0, 'dec': 26.0}",
  2: "{'jan': 46.0, 'feb': 49.0, 'mar': 53.0, 'apr': 60.0, 'may': 69.0, 'jun': 78.0, 'jul': 83.0, 'aug': 83.0, 'sep': 77.0, 'oct': 65.0, 'nov': 53.0, 'dec': 45.0}",
  3: "{'jan': 32.0, 'feb': 35.0, 'mar': 43.0, 'apr': 51.0, 'may': 61.0, 'jun': 69.0, 'jul': 73.0, 'aug': 72.0, 'sep': 65.0, 'oct': 53.0, 'nov': 42.0, 'dec': 34.0}",
  4: "{'jan': 39.0, 'feb': 41.0, 'mar': 44.0, 'apr': 46.0, 'may': 51.0, 'jun': 56.0, 'jul': 58.0, 'aug': 58.0, 'sep': 56.0, 'oct': 50.0, 'nov': 43.0, 'dec': 38.0}",
  5: "{'jan': 18.0, 'feb': 19.0, 'mar': 27.0, 'apr': 34.0, 'may': 43.0, 'jun': 52.0, 'jul': 59.0, 'aug': 57.0, 'sep': 48.0, 'oct': 37.0, 'nov': 25.0, 'dec': 18.0}",
  6: "{'jan': 16.0, 'feb': 19.0, 'mar': 27.0, 'apr': 38.0, 'may': 48.0, 'jun': 57.0, 'jul': 63.0, 'aug': 61.0, 'sep': 51.0, 'oct': 40.0, 'nov': 32.0, 'dec': 22.0}",
  7: "{'jan': 27.0, 'feb': 29.0, 'mar': 36.0, 'apr': 44.0, 'may': 54.0, 'jun': 63.0, 'jul': 68.0, 'aug': 67.0, 'sep': 60.0, 'oct': 49.0, 'nov': 40.0, 'dec': 31.0}",
  8: "{'jan': 66.0, 'feb': 66.0, 'mar': 68.0, 'apr': 69.0, 'may': 71.0, 'jun': 73.0, 'jul': 74.0, 'aug': 75.0, 'sep': 74.0, 'oct': 73.0, 'nov': 71.0, 'dec': 68.0}",
  9: "{'jan': 39.0, 'feb': 42.0, 'mar': 47.0, 'apr': 52.0, 'may': 62.0, 'jun': 69.0, 'jul': 72.0, 'aug': 72.0, 'sep': 68.0, 'oct': 57.0, 'nov': 47.0, 'dec': 41.0}",
  10: "{'jan': 43.0, 'feb': 37.0, 'mar': 54.0, 'apr': 64.0, 'may': 69.0, 'jun': 70.0, 'jul': 67.0, 'aug': 60.0, 'sep': 51.0, 'oct': 37.0, 'nov': 43.0, 'dec': 35.0}",
  11: "{'jan': 25.0, 'feb': 28.0, 'mar': 34.0, 'apr': 39.0, 'may': 47.0, 'jun': 54.0, 'jul': 60.0, 'aug': 60.0, 'sep': 51.0, 'oct': 41.0, 'nov': 32.0, 'dec': 24.0}",
  12: "{'jan': 19.0, 'feb': 23.0, 'mar': 32.0, 'apr': 42.0, 'may': 53.0, 'jun': 62.0, 'jul': 65.0, 'aug': 64.0, 'sep': 55.0, 'oct': 44.0, 'nov': 34.0, 'dec': 22.0}",
  13: "{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr': 43.0, 'may': 53.0, 'jun': 62.0, 'jul': 66.0, 'aug': 64.0, 'sep': 56.0, 'oct': 45.0, 'nov': 35.0, 'dec': 24.0}",
  14: "{'jan': 14.0, 'feb': 19.0, 'mar': 30.0, 'apr': 41.0, 'may': 52.0, 'jun': 62.0, 'jul': 67.0, 'aug': 65.0, 'sep': 55.0, 'oct': 43.0, 'nov': 31.0, 'dec': 18.0}",
  15: "{'jan': 20.0, 'feb': 24.0, 'mar': 33.0, 'apr': 44.0, 'may': 54.0, 'jun': 64.0, 'jul': 68.0, 'aug': 66.0, 'sep': 56.0, 'oct': 45.0, 'nov': 33.0, 'dec': 22.0}",
  16: "{'jan': 21.0, 'feb': 23.0, 'mar': 31.0, 'apr': 39.0, 'may': 49.0, 'jun': 59.0, 'jul': 63.0, 'aug': 62.0, 'sep': 55.0, 'oct': 42.0, 'nov': 34.0, 'dec': 26.0}",
  17: "{'jan': 41.0, 'feb': 44.0, 'mar': 50.0, 'apr': 57.0, 'may': 65.0, 'jun': 71.0, 'jul': 74.0, 'aug': 73.0, 'sep': 69.0, 'oct': 58.0, 'nov': 49.0, 'dec': 43.0}",
  18: "{'jan': 11.0, 'feb': 15.0, 'mar': 23.0, 'apr': 35.0, 'may': 45.0, 'jun': 54.0, 'jul': 60.0, 'aug': 58.0, 'sep': 51.0, 'oct': 40.0, 'nov': 31.0, 'dec': 19.0}",
  19: "{'jan': 29.0, 'feb': 31.0, 'mar': 38.0, 'apr': 47.0, 'may': 57.0, 'jun': 67.0, 'jul': 71.0, 'aug': 71.0, 'sep': 64.0, 'oct': 52.0, 'nov': 42.0, 'dec': 33.0}",
  20: "{'jan': 22.0, 'feb': 25.0, 'mar': 31.0, 'apr': 41.0, 'may': 50.0, 'jun': 60.0, 'jul': 65.0, 'aug': 65.0, 'sep': 57.0, 'oct': 47.0, 'nov': 38.0, 'dec': 28.0}",
  21: "{'jan': 17.0, 'feb': 19.0, 'mar': 26.0, 'apr': 37.0, 'may': 47.0, 'jun': 57.0, 'jul': 61.0, 'aug': 59.0, 'sep': 51.0, 'oct': 41.0, 'nov': 32.0, 'dec': 22.0}",
  22: "{'jan': 7.0, 'feb': 12.0, 'mar': 24.0, 'apr': 38.0, 'may': 50.0, 'jun': 59.0, 'jul': 64.0, 'aug': 62.0, 'sep': 53.0, 'oct': 41.0, 'nov': 27.0, 'dec': 13.0}",
  23: "{'jan': 35.0, 'feb': 38.0, 'mar': 45.0, 'apr': 52.0, 'may': 62.0, 'jun': 69.0, 'jul': 72.0, 'aug': 71.0, 'sep': 65.0, 'oct': 53.0, 'nov': 44.0, 'dec': 37.0}",
  24: "{'jan': 21.0, 'feb': 25.0, 'mar': 33.0, 'apr': 44.0, 'may': 54.0, 'jun': 64.0, 'jul': 68.0, 'aug': 66.0, 'sep': 57.0, 'oct': 45.0, 'nov': 35.0, 'dec': 24.0}",
  25: "{'jan': 13.0, 'feb': 17.0, 'mar': 24.0, 'apr': 32.0, 'may': 41.0, 'jun': 49.0, 'jul': 54.0, 'aug': 52.0, 'sep': 43.0, 'oct': 33.0, 'nov': 22.0, 'dec': 12.0}",
  26: "{'jan': 14.0, 'feb': 18.0, 'mar': 28.0, 'apr': 39.0, 'may': 51.0, 'jun': 61.0, 'jul': 66.0, 'aug': 64.0, 'sep': 53.0, 'oct': 41.0, 'nov': 28.0, 'dec': 16.0}",
  27: "{'jan': 22.0, 'feb': 25.0, 'mar': 30.0, 'apr': 34.0, 'may': 41.0, 'jun': 47.0, 'jul': 52.0, 'aug': 51.0, 'sep': 43.0, 'oct': 35.0, 'nov': 27.0, 'dec': 22.0}",
  28: "{'jan': 10.0, 'feb': 14.0, 'mar': 22.0, 'apr': 33.0, 'may': 43.0, 'jun': 53.0, 'jul': 58.0, 'aug': 56.0, 'sep': 47.0, 'oct': 36.0, 'nov': 28.0, 'dec': 17.0}",
  29: "{'jan': 16.0, 'feb': 20.0, 'mar': 30.0, 'apr': 40.0, 'may': 52.0, 'jun': 62.0, 'jul': 66.0, 'aug': 64.0, 'sep': 54.0, 'oct': 43.0, 'nov': 31.0, 'dec': 20.0}",
  30: "{'jan': 17.0, 'feb': 22.0, 'mar': 26.0, 'apr': 32.0, 'may': 41.0, 'jun': 49.0, 'jul': 54.0, 'aug': 53.0, 'sep': 47.0, 'oct': 35.0, 'nov': 25.0, 'dec': 17.0}",
  31: "{'jan': 32.0, 'feb': 34.0, 'mar': 41.0, 'apr': 48.0, 'may': 57.0, 'jun': 65.0, 'jul': 69.0, 'aug': 68.0, 'sep': 62.0, 'oct': 50.0, 'nov': 42.0, 'dec': 35.0}",
  32: "{'jan': 2.0, 'feb': 8.0, 'mar': 19.0, 'apr': 31.0, 'may': 43.0, 'jun': 52.0, 'jul': 57.0, 'aug': 56.0, 'sep': 45.0, 'oct': 32.0, 'nov': 19.0, 'dec': 6.0}",
  33: "{'jan': 15.0, 'feb': 17.0, 'mar': 26.0, 'apr': 37.0, 'may': 47.0, 'jun': 56.0, 'jul': 61.0, 'aug': 60.0, 'sep': 52.0, 'oct': 40.0, 'nov': 31.0, 'dec': 21.0}",
  34: "{'jan': 20.0, 'feb': 24.0, 'mar': 32.0, 'apr': 41.0, 'may': 52.0, 'jun': 61.0, 'jul': 65.0, 'aug': 63.0, 'sep': 56.0, 'oct': 44.0, 'nov': 35.0, 'dec': 26.0}",
  35: "{'jan': 29.0, 'feb': 33.0, 'mar': 41.0, 'apr': 50.0, 'may': 60.0, 'jun': 68.0, 'jul': 72.0, 'aug': 71.0, 'sep': 63.0, 'oct': 52.0, 'nov': 40.0, 'dec': 31.0}",
  36: "{'jan': 35.0, 'feb': 35.0, 'mar': 37.0, 'apr': 40.0, 'may': 45.0, 'jun': 49.0, 'jul': 53.0, 'aug': 53.0, 'sep': 48.0, 'oct': 42.0, 'nov': 38.0, 'dec': 34.0}",
  37: "{'jan': 23.0, 'feb': 25.0, 'mar': 33.0, 'apr': 42.0, 'may': 51.0, 'jun': 61.0, 'jul': 66.0, 'aug': 64.0, 'sep': 57.0, 'oct': 45.0, 'nov': 36.0, 'dec': 28.0}",
  38: "{'jan': 21.0, 'feb': 24.0, 'mar': 30.0, 'apr': 40.0, 'may': 49.0, 'jun': 58.0, 'jul': 64.0, 'aug': 63.0, 'sep': 55.0, 'oct': 44.0, 'nov': 36.0, 'dec': 26.0}",
  39: "{'jan': 37.0, 'feb': 41.0, 'mar': 47.0, 'apr': 54.0, 'may': 62.0, 'jun': 70.0, 'jul': 73.0, 'aug': 72.0, 'sep': 67.0, 'oct': 55.0, 'nov': 47.0, 'dec': 39.0}",
  40: "{'jan': 10.0, 'feb': 14.0, 'mar': 24.0, 'apr': 34.0, 'may': 46.0, 'jun': 55.0, 'jul': 62.0, 'aug': 60.0, 'sep': 49.0, 'oct': 36.0, 'nov': 23.0, 'dec': 12.0}",
  41: "{'jan': 28.0, 'feb': 32.0, 'mar': 39.0, 'apr': 47.0, 'may': 57.0, 'jun': 65.0, 'jul': 69.0, 'aug': 68.0, 'sep': 61.0, 'oct': 49.0, 'nov': 39.0, 'dec': 31.0}",
  42: "{'jan': 42.0, 'feb': 45.0, 'mar': 51.0, 'apr': 59.0, 'may': 67.0, 'jun': 72.0, 'jul': 74.0, 'aug': 75.0, 'sep': 69.0, 'oct': 61.0, 'nov': 51.0, 'dec': 42.0}",
  43: "{'jan': 26.0, 'feb': 31.0, 'mar': 38.0, 'apr': 43.0, 'may': 52.0, 'jun': 61.0, 'jul': 69.0, 'aug': 67.0, 'sep': 58.0, 'oct': 46.0, 'nov': 36.0, 'dec': 27.0}",
  44: "{'jan': 7.0, 'feb': 10.0, 'mar': 19.0, 'apr': 31.0, 'may': 42.0, 'jun': 51.0, 'jul': 56.0, 'aug': 54.0, 'sep': 46.0, 'oct': 35.0, 'nov': 27.0, 'dec': 14.0}",
  45: "{'jan': 28.0, 'feb': 31.0, 'mar': 37.0, 'apr': 46.0, 'may': 55.0, 'jun': 65.0, 'jul': 69.0, 'aug': 67.0, 'sep': 60.0, 'oct': 48.0, 'nov': 39.0, 'dec': 31.0}",
  46: "{'jan': 34.0, 'feb': 33.0, 'mar': 35.0, 'apr': 38.0, 'may': 43.0, 'jun': 48.0, 'jul': 51.0, 'aug': 51.0, 'sep': 46.0, 'oct': 40.0, 'nov': 36.0, 'dec': 33.0}",
  47: "{'jan': 26.0, 'feb': 29.0, 'mar': 35.0, 'apr': 44.0, 'may': 53.0, 'jun': 62.0, 'jul': 66.0, 'aug': 65.0, 'sep': 57.0, 'oct': 45.0, 'nov': 37.0, 'dec': 29.0}",
  48: "{'jan': 11.0, 'feb': 15.0, 'mar': 25.0, 'apr': 36.0, 'may': 46.0, 'jun': 56.0, 'jul': 61.0, 'aug': 59.0, 'sep': 50.0, 'oct': 39.0, 'nov': 28.0, 'dec': 16.0}",
  49: "{'jan': 18.0, 'feb': 19.0, 'mar': 24.0, 'apr': 31.0, 'may': 40.0, 'jun': 49.0, 'jul': 56.0, 'aug': 54.0, 'sep': 45.0, 'oct': 34.0, 'nov': 24.0, 'dec': 17.0}"},
 'average rain': {0: "{'jan': 4.65, 'feb': 5.28, 'mar': 5.95, 'apr': 4.02, 'may': 3.54, 'jun': 4.07, 'jul': 5.24, 'aug': 3.96, 'sep': 3.97, 'oct': 2.92, 'nov': 4.61, 'dec': 4.86}",
  1: "{'jan': 5.35, 'feb': 4.13, 'mar': 3.78, 'apr': 2.94, 'may': 3.4, 'jun': 3.24, 'jul': 4.6, 'aug': 5.73, 'sep': 8.64, 'oct': 8.63, 'nov': 5.99, 'dec': 5.84}",
  2: "{'jan': 4.0, 'feb': 4.0, 'mar': 3.0, 'apr': 2.0, 'may': 1.0, 'jun': 1.0, 'jul': 4.0, 'aug': 5.0, 'sep': 3.0, 'oct': 3.0, 'nov': 2.0, 'dec': 4.0}",
  3: "{'jan': 8.0, 'feb': 9.0, 'mar': 9.0, 'apr': 11.0, 'may': 11.0, 'jun': 8.0, 'jul': 8.0, 'aug': 6.0, 'sep': 7.0, 'oct': 8.0, 'nov': 8.0, 'dec': 9.0}",
  4: "{'jan': 3.64, 'feb': 3.47, 'mar': 2.75, 'apr': 1.15, 'may': 0.68, 'jun': 0.21, 'jul': 0.0, 'aug': 0.05, 'sep': 0.29, 'oct': 0.95, 'nov': 2.08, 'dec': 3.25}",
  5: "{'jan': 9999.0, 'feb': 9999.0, 'mar': 9999.0, 'apr': 9999.0, 'may': 9999.0, 'jun': 9999.0, 'jul': 9999.0, 'aug': 9999.0, 'sep': 9999.0, 'oct': 9999.0, 'nov': 9999.0, 'dec': 9999.0}",
  6: "{'jan': 3.66, 'feb': 2.64, 'mar': 3.62, 'apr': 3.82, 'may': 3.98, 'jun': 3.82, 'jul': 3.94, 'aug': 3.82, 'sep': 3.82, 'oct': 3.9, 'nov': 3.78, 'dec': 3.43}",
  7: "{'jan': 3.41, 'feb': 3.07, 'mar': 4.31, 'apr': 3.88, 'may': 4.25, 'jun': 4.0, 'jul': 4.09, 'aug': 4.36, 'sep': 4.13, 'oct': 3.42, 'nov': 3.48, 'dec': 3.65}",
  8: "{'jan': 14.0, 'feb': 11.0, 'mar': 13.0, 'apr': 12.0, 'may': 11.0, 'jun': 12.0, 'jul': 14.0, 'aug': 13.0, 'sep': 13.0, 'oct': 13.0, 'nov': 13.0, 'dec': 15.0}",
  9: "{'jan': 4.34, 'feb': 4.85, 'mar': 5.94, 'apr': 3.06, 'may': 3.47, 'jun': 7.73, 'jul': 7.17, 'aug': 7.35, 'sep': 4.69, 'oct': 3.23, 'nov': 3.5, 'dec': 3.9}",
  10: "{'jan': 8.0, 'feb': 11.0, 'mar': 7.0, 'apr': 7.0, 'may': 10.0, 'jun': 12.0, 'jul': 10.0, 'aug': 9.0, 'sep': 10.0, 'oct': 10.0, 'nov': 12.0, 'dec': 11.0}",
  11: "{'jan': 10.0, 'feb': 9.0, 'mar': 10.0, 'apr': 8.0, 'may': 7.0, 'jun': 5.0, 'jul': 2.0, 'aug': 2.0, 'sep': 3.0, 'oct': 5.0, 'nov': 10.0, 'dec': 11.0}",
  12: "{'jan': 1.82, 'feb': 1.81, 'mar': 2.63, 'apr': 3.51, 'may': 4.24, 'jun': 4.46, 'jul': 3.94, 'aug': 3.24, 'sep': 2.9, 'oct': 3.15, 'nov': 3.21, 'dec': 2.52}",
  13: "{'jan': 12.0, 'feb': 10.0, 'mar': 11.0, 'apr': 12.0, 'may': 13.0, 'jun': 11.0, 'jul': 10.0, 'aug': 8.0, 'sep': 8.0, 'oct': 8.0, 'nov': 10.0, 'dec': 12.0}",
  14: "{'jan': 7.0, 'feb': 7.0, 'mar': 9.0, 'apr': 11.0, 'may': 12.0, 'jun': 11.0, 'jul': 10.0, 'aug': 9.0, 'sep': 8.0, 'oct': 8.0, 'nov': 8.0, 'dec': 8.0}",
  15: "{'jan': 0.86, 'feb': 1.32, 'mar': 2.49, 'apr': 3.53, 'may': 4.91, 'jun': 5.4, 'jul': 3.82, 'aug': 4.24, 'sep': 3.66, 'oct': 3.03, 'nov': 1.85, 'dec': 1.35}",
  16: "{'jan': 3.15, 'feb': 3.07, 'mar': 4.06, 'apr': 3.66, 'may': 4.61, 'jun': 4.41, 'jul': 4.17, 'aug': 3.58, 'sep': 3.15, 'oct': 2.68, 'nov': 3.35, 'dec': 3.7}",
  17: "{'jan': 5.72, 'feb': 5.04, 'mar': 4.41, 'apr': 4.46, 'may': 4.89, 'jun': 6.41, 'jul': 4.96, 'aug': 5.82, 'sep': 4.54, 'oct': 4.7, 'nov': 4.1, 'dec': 5.6}",
  18: "{'jan': 2.61, 'feb': 2.43, 'mar': 3.37, 'apr': 3.79, 'may': 3.69, 'jun': 3.56, 'jul': 3.42, 'aug': 3.31, 'sep': 3.74, 'oct': 4.36, 'nov': 4.36, 'dec': 3.24}",
  19: "{'jan': 3.32, 'feb': 2.94, 'mar': 4.53, 'apr': 3.66, 'may': 4.2, 'jun': 4.17, 'jul': 4.56, 'aug': 3.88, 'sep': 4.76, 'oct': 3.89, 'nov': 3.8, 'dec': 3.56}",

In [40]:
f = open("i.txt","w")
f.write( str(i) )
f.close()

In [39]:
json_object = json.dumps(i, indent = 4)   
json_object

TypeError: Object of type Polygon is not JSON serializable

In [32]:
# Saving to json
json = json.dumps(i)
f = open("../../templates/resources/data/test.json","w")
f.write(json)
f.close()

TypeError: Object of type method is not JSON serializable